---
server:
  port: 8818
spring:
  application:
    name: provider-dict-mybatis-redis
  profiles: provider-dict-mybatis-redis
  # 数据源配置
  #https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: your url
      username: your user name
      password: your password
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #检测连接是否有效的sql
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # PSCache Mysql下建议关闭
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      #spring.datasource.druid.max-open-prepared-statements= #等价于上面的max-pool-prepared-statement-per-connection-size
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      #启动项目后访问 http://127.0.0.1:8080/druid
      #是否启用StatFilter默认值true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: \*.js,\*.gif,\*.jpg,\*.bmp,\*.png,\*.css,\*.ico,/druid/*
        #缺省sessionStatMaxCount是1000个
        session-stat-max-count: 1000
      stat-view-servlet:
        login-username: your user name
        login-password: your password
  redis:
    database: 14
    host: your host
    port: your port
    password: your password
    timeout: 0
    pool:
      max-active: 1000
      max-wait: -1
      max-idle: 100
      min-idle: 0
eureka:
  instance:
    prefer-ip-address: true
#    appname: provider-user
    metadata-map:
      zone: local
      function: provider-dict-mybatis-redis
  client:
    serviceUrl:
      defaultZone: http://peer1:peer1@peer1:8800/eureka/,http://peer2:peer2@peer2:8801/eureka/
    healthcheck:
      enabled: true
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
  version: @project.version@
mybatis:
  type-aliases-package: com.kkl.demo.entity.md
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  configuration:
    cache-enabled: true
logging:
  level:
    org.mybatis: debug
    com.kkl.demo: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql