spring:
  profiles: consumer-user-ribbon
  application:
    name: consumer-user-ribbon

server:
  port: 8820

eureka:
  instance:
    prefer-ip-address: true
#    appname: consumer-user-ribbon
    metadata-map:
      zone: local
      function: consumer-user-ribbon
  client:
    serviceUrl:
      defaultZone: http://peer1:peer1@peer1:8800/eureka/,http://peer2:peer2@peer2:8801/eureka/
    healthcheck:
      enabled: true
provider-user:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@