---
spring:
  profiles: zuul1
  application:
    name: zuul-gateway
server:
  port: 8870
eureka:
  instance:
    prefer-ip-address: true
#    appname: provider-user
    metadata-map:
      zone: local
      function: zuul-gateway
  client:
    serviceUrl:
      defaultZone: http://peer1:peer1@localhost:8800/eureka/,http://peer2:peer2@localhost:8801/eureka/
    healthcheck:
      enabled: true
zuul:
  ignoredServices: '*'
  routes:
    provider-user: /**
info:
  name: @project.artifactId@
  desc: eureka服务器
  version: @project.version@
logging:
  level:
    com.netflix: debug

---
spring:
  profiles: zuul2
  application:
    name: zuul-gateway
server:
  port: 8871
eureka:
  instance:
    prefer-ip-address: true
#    appname: provider-user
    metadata-map:
      zone: local
      function: zuul-gateway
  client:
    serviceUrl:
      defaultZone: http://peer1:peer1@localhost:8800/eureka/,http://peer2:peer2@localhost:8801/eureka/
    healthcheck:
      enabled: true
zuul:
  ignoredServices: '*'
  routes:
    provider-user: /**
info:
  name: @project.artifactId@
  desc: eureka服务器
  version: @project.version@
logging:
  level:
    com.netflix: debug